Create andy-barrett.yml
uwhackweek/event-page-2024 pull request #23
Opened 2024-06-18 19:37 UTC by andypbarrett

add bio

2024-06-18 19:44 UTC, agentrrb approved these changes

2024-06-18 22:03 UTC, scottyhq commented on team/andy-barrett.yaml
> +    A FEW SENTENCES ABOUT YOU, MULTIPLE LINES ARE FINE
@andypbarrett don't forget this bit! once sentence is fine, or you can just leave it blank

2024-06-18 22:04 UTC, scottyhq requested changes
see above comment on missing bio section

2024-07-29 22:45 UTC, aaarendt approved these changes

2024-07-29 22:46 UTC, aaarendt commented
@scottyhq let's merge this for now - we can ask Andy to add more detail the next time we speak

2024-07-29 22:56 UTC, scottyhq approved these changes

2024-07-29 22:56 UTC, merged