jensen bio page
uwhackweek/event-page-2024 pull request #28
Opened 2024-06-18 19:39 UTC by ZihengSun

2024-06-18 20:11 UTC, JessicaS11 commented
@ZihengSun Could you please rename your file to use a dash instead of an underscore (`jensen-sun.yaml`)?

2024-06-18 20:40 UTC, ZihengSun commented
> @ZihengSun Could you please rename your file to use a dash instead of an underscore (`jensen-sun.yaml`)?

Oh yeah sure.

2024-06-18 20:41 UTC, ZihengSun commented
Done, but the action keeps failing. I am looking into it.

2024-06-18 20:45 UTC, ZihengSun commented
My bad. I always has problems with indentation.

2024-06-18 22:13 UTC, scottyhq commented on team/jensen-sun.yaml
> +  bio: I am a workflow guy and practitioner on using AI to address cool Earth scientific questions.
```suggestion
  bio: > 
    I am a workflow guy and practitioner on using AI to address cool Earth scientific questions. 
```

2024-06-18 22:13 UTC, scottyhq commented on team/jensen-sun.yaml
> +  bio: I am a workflow guy and practitioner on using AI to address cool Earth scientific questions.
https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines/21699210#21699210

2024-06-18 22:20 UTC, scottyhq requested changes
see above to get the bio to render correctly

2024-06-19 15:29 UTC, ZihengSun commented
@scottyhq thanks! corrected.

2024-06-19 15:36 UTC, ZihengSun commented
The intro page doesn't pop up because I put baskets in my name. Removing ( and ) did the trick :)

2024-06-21 17:44 UTC, scottyhq approved these changes

2024-06-21 17:44 UTC, merged