Create jesslyn-difiori
uwhackweek/event-page-2024 pull request #29
Opened 2024-06-18 19:40 UTC by jkdifiori

created bio

2024-06-18 19:46 UTC, agentrrb approved these changes

2024-06-18 22:15 UTC, scottyhq requested changes

2024-06-18 22:15 UTC, scottyhq commented on team/jesslyn-difiori
> +    A FEW SENTENCES ABOUT YOU, MULTIPLE LINES ARE FINE
thanks @jkdifiori don't forget to modify these other sections in CAPS before we can merge your bio

2024-06-27 16:19 UTC, scottyhq commented on team/jesslyn-difiori
> +    - Data Visualization
```suggestion
expertise:
    - Scientific Communication
    - Data Visualization
```

2024-06-27 16:22 UTC, scottyhq commented on team/jesslyn-difiori
> +    - Scientific Communication
```suggestion
  bio: >
    Jesslyn is a Technical Writer at the National Snow and Ice Data Center, where she writes and maintains scientific documentation, metadata, and web content for cryospheric data. She works primarily with NASA SnowEx, MODIS, and VIIRS data sets. 
  expertise:
    - Scientific Communication
```

2024-06-27 16:23 UTC, scottyhq commented on team/jesslyn-difiori
> +    - Scientific Communication
@jkdifiori see suggestion above to add back missing 'expertise:' header

2024-06-27 16:33 UTC, scottyhq commented on team/jesslyn-difiori
> +    - Data Visualization
```suggestion
  expertise:     
    - Scientific Communication
    - Data Visualization
```

be sure to match indentation levels

2024-06-27 16:35 UTC, scottyhq commented on team/jesslyn-difiori
> +    - Data Visualization
(if you click the 'commit suggestion' button above should be all set. the formatting is very picky!)

2024-06-27 16:45 UTC, scottyhq commented
@jkdifiori sorry I missed this earlier. You'll also need to rename your file `jesslyn-difiori` -> `jesslyn-difiori.yaml`

2024-06-27 16:49 UTC, scottyhq approved these changes

2024-06-27 16:49 UTC, scottyhq commented
thanks!

2024-06-27 16:49 UTC, merged